name: Android Publish Play Store (Still in development)

# env:
#   # The name of the main module repository
#   main_project_module: android

#   # The name of the Play Store

on:
  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./android/gradlew

      - name: Run Tests
        run: ./android/gradlew test

      - name: Build Project
        run: ./android/radlew build

      - name: Build Release AAB
        run: ./android/gradlew bundleRelease

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
#           signingKeyBase64: ${{ secrets.SIGN_KEY }}
#           alias: ${{ secrets.ALIAS }}
#           keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
#           keyPassword: ${{ secrets.KEY_PASSWORD }}

#       - name: Deploy to Play Store
#         uses: r0adkll/upload-google-play@v1
#         with:
#           serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT}}
#           packageName: com.tomerpacific.laundry
#           releaseFiles: app/build/outputs/bundle/release/app-release.aab
#           track: production
